---
- hosts: webservers
  become: true
  tasks:
   - name: stop the preivous running docker images for valaxy
     shell: docker stop valaxy_demo
   - name: Remove the stopped container
     shell: docker rm -f valaxy_demo
   - name: Remove the docker images created using earlier docker file
     shell: docker image rm -f valxy_demo

   - name: Create a new container using image from docker hub
     shell: docker run -it -d --name valaxy_demohub -p 8090:8080 clouddevopspractice/valaxy_demo
